export const SET_AUTH = 'APP/SET_AUTH'
export const SET_TOKEN = 'APP/SET_TOKEN'

export const SET_MENU_COLLAPSED = 'APP/MENU/SET_COLLAPSED'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SET_ACTION_MODAL_VISIBILITY = 'APP/SET_ACTION_MODAL_VISIBILITY'
export const SET_ACTION = 'APP/SET_ACTION'
export const SET_TABLE_SELECTED_ROWS = 'APP/SET_TABLE_SELECTED_ROWS'
