version: '3.0'
services:
    nginx:
        container_name: college-site-v3_nginx
        hostname: college-site-v3_nginx
        build: .
        ports:
            - '80:80'
        depends_on:
            - api
            - public
    api:
        container_name: college-site-v3_api
        hostname: college-site-v3_api
        build: api/
        restart: unless-stopped
    public:
        container_name: college-site-v3_public
        hostname: college-site-v3_public
        build: public/
        restart: unless-stopped
