version: '3.0'
services:
    nginx:
        container_name: college-site-v3_nginx
        hostname: college-site-v3_nginx
        build: .
        ports:
            - '80:80'
        depends_on:
            - api
            - public
    api:
        container_name: college-site-v3_api
        hostname: college-site-v3_api
        build: api/
        restart: unless-stopped
        volumes:
            - type: bind
              source: ./api/app-settings.json
              target: /ts-built/app-settings.json
        depends_on:
            - postgres
            - redis
    public:
        container_name: college-site-v3_public
        hostname: college-site-v3_public
        build: public/
        restart: unless-stopped
        depends_on:
            - api

    postgres:
        image: 'postgres:14'
        container_name: 'college-site-v3_postgres'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - ./db/postgres.sql:/docker-entrypoint-initdb.d/db.sql
            - ./db/volumes/postgres:/var/lib/postgresql/data
        restart: unless-stopped
        
    redis:
        image: 'redis:7'
        container_name: 'college-site-v3_redis'
        volumes:
            - ./db/volumes/redis:/data
        ports:
            - '6379:6379'
