version: '3.0'
services:
    api:
        build: api/
        ports:
            - '8080:8080'
    admin:
        build: admin/
        ports:
            - '3000:3000'
    public:
        build: public/
        ports:
            - '80:80'
