/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IUser = t.iface([], {
  "id": t.opt("string"),
  "email": "string",
  "name": "string",
  "status": t.union(t.lit('admin'), t.lit('moderator'), t.lit('banned'), t.lit('unconfirmed')),
  "description": t.opt("string"),
  "tags": t.opt(t.array("string")),
  "timestamp": "number",
  "lastUpdateTimestamp": t.opt("number"),
});

export const IUserPutByAdmin = t.iface([], {
  "status": t.opt(t.union(t.lit('admin'), t.lit('moderator'), t.lit('banned'), t.lit('unconfirmed'))),
  "description": t.opt("string"),
  "tags": t.opt(t.array("string")),
});

export const IUserPutByModerator = t.iface([], {
  "description": t.opt("string"),
  "tags": t.opt(t.array("string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  IUser,
  IUserPutByAdmin,
  IUserPutByModerator,
};
export default exportedTypeSuite;
