/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const IMenuElement = t.iface([], {
    title: 'string',
    link: 'string',
    hidden: 'boolean',
    children: t.array('IMenuElement')
})

export const IMenuBlock = t.iface([], {
    id: t.opt('string'),
    menu: t.array('IMenuElement'),
    selected: t.opt('boolean'),
    timestamp: 'number',
    lastUpdateTimestamp: t.opt('number')
})

export const IMenuBlockPost = t.iface([], {
    menu: t.array('IMenuElement'),
    selected: t.opt('boolean')
})

export const IMenuBlockPut = t.iface([], {
    menu: t.array('IMenuElement'),
    selected: t.opt('boolean')
})

const exportedTypeSuite: t.ITypeSuite = {
    IMenuElement,
    IMenuBlock,
    IMenuBlockPost,
    IMenuBlockPut
}
export default exportedTypeSuite
