name: Check API

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        steps:
            - uses: actions/checkout@v2
            - run: docker-compose up -d postgres
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.13.1
            - run: |
                  cd api
                  npm i
            - run: |
                  cd api
                  echo "${{ secrets.test }}" > .env.test
            - run: npm run test-server
            - run: npm run test
