name: Check API

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run Postgres
              run: docker-compose up -d postgres
              env:
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.13.1
            - name: npm i
              run: |
                  cd api
                  npm i
            - name: Create .env.test file
              env:
                  API_ENV_TEST: ${{ secrets.API_ENV_TEST }}
              run: |
                  cd api
                  echo "$API_ENV_TEST" > .env.test
            - name: Start server for testing
              run: |
                  cd api
                  npm run build
                  npm run test-server & wait-on http://localhost:8081
            - name: Run tests
              run: |
                  cd api
                  npm run test
